version: '3'
services:
  db:
    image: mysqldb
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  auth:
    image: myauthimage
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  upload:
    image: myuploadimage
    build:
      context: ./upload
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PASSWORD: password
    ports:
      - 5000:5000
    volumes:
      - static-data:/usr/share/nginx/html
  file_system:
    build: ./file_system
    volumes:
      - data:/mnt/data
  web:
    image: mynginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - upload
    volumes:
      - static-data:/usr/share/nginx/html
      - nginx-conf:/etc/nginx/sites-enabled
volumes:
  mysql-data: {}
  nginx-conf: {}
  static-data: {}
  data: {}
