version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: video_streaming
    volumes:
      - mysql-data:/var/lib/mysql
  auth:
    image: myauthimage
    build:
      context: ./auth
      dockerfile: Dockerfile
  upload:
    image: myuploadimage
    build:
      context: ./upload
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PASSWORD: password
  file_system:
    build: ./file_system
    volumes:
      - data:/mnt/data
  streaming:
    image: mystreamingimage
    build:
      context: ./streaming
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PASSWORD: password
      FILE_SYSTEM_HOST: file_system
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static-data:/usr/share/nginx/html
volumes:
  mysql-data:
  data:
  static-data:

